# Generated by Django 5.0.6 on 2024-05-31 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_alter_user_token'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise', verbose_name='assignments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.user', verbose_name='assignments')),
            ],
        ),
    ]
