# Generated by Django 5.0.6 on 2024-05-31 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_user_token'),
        ('assignments', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='access.user'),
        ),
    ]
