# Generated by Django 5.0.6 on 2024-06-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_bucket_frame_assignment_frame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ['context', 'start']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='num_exercises',
            field=models.PositiveSmallIntegerField(blank=True, help_text='If blank, it will be populated with total number of exercises', null=True),
        ),
    ]
