# Generated by Django 5.0.6 on 2024-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_alter_assignment_options'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='exercises',
            field=models.ManyToManyField(to='exercises.exercise'),
        ),
    ]
