# Generated by Django 5.0.6 on 2024-06-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_alter_batch_exercise_alter_batch_frame'),
        ('exercises', '0002_topic_exercise_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='Pack',
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name_plural': 'Batches'},
        ),
    ]
