# Generated by Django 5.0.6 on 2024-06-16 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_rename_batch_pack_alter_pack_options'),
        ('exercises', '0002_topic_exercise_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={},
        ),
        migrations.AlterField(
            model_name='pack',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs', to='assignments.frame'),
        ),
    ]
