# Generated by Django 5.0.6 on 2024-06-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_alter_pack_options_alter_pack_exercise_and_more'),
        ('exercises', '0002_topic_exercise_topic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pack',
            unique_together={('frame', 'exercise')},
        ),
    ]
