# Generated by Django 5.0.6 on 2024-07-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_alter_pack_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='bucket',
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
    ]
