# Generated by Django 5.0.6 on 2024-07-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_remove_frame_bucket_delete_bucket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pack',
        ),
    ]
