# Generated by Django 5.0.6 on 2024-07-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_delete_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='frame',
        ),
    ]
