# Generated by Django 5.0.6 on 2024-07-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0018_remove_assignment_frame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
