# Generated by Django 5.0.6 on 2024-08-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0019_delete_frame'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='exercise',
        ),
    ]
