# Generated by Django 5.0.6 on 2024-08-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_alter_assignment_unique_together_and_more'),
        ('chunks', '0005_alter_chunk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='chunk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='chunks.chunk'),
            preserve_default=False,
        ),
    ]
