# Generated by Django 5.0.6 on 2024-08-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_user_token'),
        ('assignments', '0021_assignment_chunk'),
        ('chunks', '0005_alter_chunk_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('user', 'chunk')},
        ),
    ]
