# Generated by Django 5.2.1 on 2026-01-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_user_token'),
        ('assignments', '0022_alter_assignment_unique_together'),
        ('chunks', '0011_chunk_pass_to_put'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chunks.chunk'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='access.user'),
        ),
    ]
