# Generated by Django 5.0.6 on 2024-06-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.SlugField(max_length=128)),
                ('secondary', models.SlugField(max_length=128)),
            ],
            options={
                'unique_together': {('primary', 'secondary')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.topic'),
        ),
    ]
