# Generated by Django 5.0.6 on 2024-06-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_topic_exercise_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['topic', 'slug']},
        ),
    ]
