# Generated by Django 5.0.6 on 2024-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_exercise_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
