# Generated by Django 5.0.6 on 2025-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_topic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
