# Generated by Django 5.0.6 on 2024-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='puttable',
            field=models.BooleanField(default=False),
        ),
    ]
