# Generated by Django 5.0.6 on 2024-07-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0004_alter_chunk_puttable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ('frame', 'exercise')},
        ),
    ]
