# Generated by Django 5.0.6 on 2024-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0005_alter_chunk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
