# Generated by Django 5.0.6 on 2024-08-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0006_chunk_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ('frame', 'order', 'exercise')},
        ),
    ]
