# Generated by Django 5.0.6 on 2024-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0007_alter_chunk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='hits',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
