# Generated by Django 5.0.6 on 2025-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0008_chunk_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
