# Generated by Django 5.0.6 on 2025-05-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0009_alter_chunk_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ('order',)},
        ),
    ]
