# Generated by Django 5.2.1 on 2025-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0010_alter_chunk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='pass_to_put',
            field=models.BooleanField(default=False, help_text='If True, the exercise must pass the tests to be puttable.'),
        ),
    ]
