# Generated by Django 5.0.6 on 2024-07-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0003_alter_frame_end_alter_frame_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='exercises',
        ),
    ]
