# Generated by Django 5.0.6 on 2024-08-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0004_remove_frame_exercises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ['context', 'start', 'bucket']},
        ),
    ]
