# Generated by Django 5.0.6 on 2025-05-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_alter_frame_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ['name']},
        ),
    ]
