# Generated by Django 5.2.1 on 2025-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0006_alter_bucket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
