# Generated by Django 5.0.6 on 2024-05-29 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='access.context')),
            ],
            options={
                'unique_together': {('name', 'context')},
            },
        ),
    ]
