# Generated by Django 5.0.6 on 2024-05-30 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
